### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by Y-st** [iavael/EnableContactsGroups#1]
This module add much-needed functionality that is otherwise missing, but there is no license file included. I don't know what my rights are with this software. Would you mind adding a license to this software? Using the GNU GPLv3+ would be preferable, but if you add any license at all, I would know if I could install this while still abiding by my free-software-only installation policy.

**Comment by iavael** [comment]
Added LGPLv3+ since runtime linking takes place.

**Comment by Y-st** [comment]
Sweet! Thank you very much for adding a free software license and for writing this great application in the first place!
